import { mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";

/**
 * Video information from KlingAI task result.
 */
export interface VideoInfo {
  /** Generated video ID; globally unique */
  id: string;
  /** URL for generated video */
  url: string;
  /** Total video duration in seconds */
  duration: string;
}

/**
 * Task result containing videos array.
 */
export interface TaskResult {
  videos: VideoInfo[];
}

/**
 * KlingAI task response structure (from Query Task API).
 */
export interface KlingTaskResponse {
  /** Error code; 0 = success */
  code: number;
  /** Error message */
  message: string;
  /** Request ID, generated by the system */
  request_id: string;
  data: {
    /** Task ID, generated by the system */
    task_id: string;
    /** Task status: submitted, processing, succeed, failed */
    task_status: "submitted" | "processing" | "succeed" | "failed";
    /** Task status message, shows failure reason when failed */
    task_status_msg?: string;
    /** Task creation parameters */
    task_info?: {
      /** Customer-defined task ID */
      external_task_id?: string;
    };
    /** Task creation time, Unix timestamp in ms */
    created_at: number;
    /** Task update time, Unix timestamp in ms */
    updated_at: number;
    /** Task result with videos */
    task_result?: TaskResult;
  };
}

/**
 * Result of video download operation.
 */
export interface DownloadResult {
  success: boolean;
  filePath?: string;
  error?: string;
  videoId: string;
  duration: string;
  url: string;
}

/**
 * Options for video download.
 */
export interface DownloadOptions {
  /** Output directory for downloaded videos */
  outputDir?: string;
  /** Custom filename (without extension) */
  filename?: string;
  /** Run ID to include in filename */
  runId?: string;
  /** Overwrite existing files */
  overwrite?: boolean;
}

/**
 * Extracts video information from KlingAI task response.
 * @throws Error if task failed or no videos available
 */
export function extractVideosFromResponse(response: KlingTaskResponse): VideoInfo[] {
  if (response.code !== 0) {
    throw new Error(`KlingAI API error: ${response.message} (code: ${response.code})`);
  }

  if (response.data.task_status === "failed") {
    throw new Error(
      `Task failed: ${response.data.task_status_msg || "Unknown error"}`
    );
  }

  if (response.data.task_status !== "succeed") {
    throw new Error(
      `Task not completed. Status: ${response.data.task_status}, Message: ${response.data.task_status_msg || "Processing"}`
    );
  }

  if (!response.data.task_result?.videos?.length) {
    throw new Error("No videos found in task result");
  }

  return response.data.task_result.videos;
}

/**
 * Checks if task is ready for video download.
 */
export function isTaskReadyForDownload(response: KlingTaskResponse): boolean {
  return (
    response.code === 0 &&
    response.data.task_status === "succeed" &&
    !!response.data.task_result?.videos?.length
  );
}

/**
 * Generates filename for video based on options.
 * Format: {runId}_{videoId}.mp4 or {filename}.mp4
 */
export function generateVideoFilename(
  videoId: string,
  options: DownloadOptions = {}
): string {
  if (options.filename) {
    return `${options.filename}.mp4`;
  }

  if (options.runId) {
    return `${options.runId}_${videoId}.mp4`;
  }

  return `${videoId}.mp4`;
}

/**
 * Downloads a video from URL to local file.
 * @param videoUrl - URL of the video to download
 * @param options - Download options
 * @returns Path to the downloaded file
 */
export async function downloadVideo(
  videoUrl: string,
  options: DownloadOptions & { videoId?: string } = {}
): Promise<string> {
  const {
    outputDir = "./output/videos",
    overwrite = false,
    videoId = `video_${Date.now()}`,
  } = options;

  // Ensure output directory exists
  await mkdir(outputDir, { recursive: true });

  // Generate filename
  const filename = generateVideoFilename(videoId, options);
  const filePath = join(outputDir, filename);

  // Check if file exists
  if (!overwrite) {
    const file = Bun.file(filePath);
    if (await file.exists()) {
      throw new Error(
        `File already exists: ${filePath}. Set overwrite: true to replace.`
      );
    }
  }

  // Download video
  const response = await fetch(videoUrl);

  if (!response.ok) {
    throw new Error(
      `Failed to download video: ${response.status} ${response.statusText}`
    );
  }

  const arrayBuffer = await response.arrayBuffer();
  await Bun.write(filePath, arrayBuffer);

  return filePath;
}

/**
 * Downloads all videos from a completed KlingAI task.
 * @param taskResponse - KlingAI task response with videos
 * @param options - Download options
 * @returns Array of download results
 */
export async function downloadVideosFromTask(
  taskResponse: KlingTaskResponse,
  options: DownloadOptions = {}
): Promise<DownloadResult[]> {
  const videos = extractVideosFromResponse(taskResponse);
  const results: DownloadResult[] = [];

  for (let i = 0; i < videos.length; i++) {
    const video = videos[i]!;
    try {
      // Add index suffix if multiple videos
      const indexSuffix = videos.length > 1 ? `_${i + 1}` : "";
      const filenameWithIndex = options.filename
        ? `${options.filename}${indexSuffix}`
        : undefined;

      const filePath = await downloadVideo(video.url, {
        ...options,
        filename: filenameWithIndex,
        videoId: video.id,
      });

      results.push({
        success: true,
        filePath,
        videoId: video.id,
        duration: video.duration,
        url: video.url,
      });
    } catch (error) {
      results.push({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
        videoId: video.id,
        duration: video.duration,
        url: video.url,
      });
    }
  }

  return results;
}

/**
 * Downloads a single video by URL with run ID in filename.
 * Convenience function for CLI usage.
 */
export async function downloadVideoForRun(
  videoUrl: string,
  runId: string,
  videoId: string,
  outputDir = "./output/videos"
): Promise<string> {
  return downloadVideo(videoUrl, {
    outputDir,
    runId,
    videoId,
    overwrite: true,
  });
}
